[project]
name = 'bitcoin-oracle'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[repl]
costs_version = 2

# [repl.analysis]
# passes = ['check_checker']

# [repl.analysis.check_checker]
# strict = false
# trusted_sender = false
# trusted_caller = false
# callee_filter = false

[contracts.clarity-bitcoin-v1-02]
path = 'contracts/clarity-bitcoin-v1-02.clar'
clarity_version = 2
epoch = 2.1

[contracts.utils]
path = 'contracts/utils.clar'
clarity_version = 2
epoch = 2.1

[contracts.oracle-v1-02]
path = 'contracts/oracle-v1-02.clar'
clarity_version = 2
epoch = 2.1
depends_on = ["clarity-bitcoin-v1-02", "oracle-registry-v1-01"]

[contracts.oracle-registry-v1-01]
path = 'contracts/oracle-registry-v1-01.clar'
clarity_version = 2
epoch = 2.1
depends_on = []
