version: '3'
services:
  # Collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.88.0
    command: ['--config=/conf/collector-config.yaml']
    volumes:
      - ./docker/collector-config.yaml:/conf/collector-config.yaml
    ports:
      - '9464:9464' # Prometheus
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
    depends_on:
      - zipkin-all-in-one

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:2.24
    ports:
      - '9411:9411'

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.47.2
    volumes:
      - ./docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
