name: Continuous Deployment (CD)
on:
  push:
    branches:
      - production
  workflow_dispatch:
    inputs:
      projects:
        description: 'Projects to build, (comma separated)'
        required: true
        default: 'api-server'

jobs:
  extract:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      projects: ${{ steps.extract_projects.outputs.result }}
    steps:
      - run: |
          echo "Projects: $PROJECTS"
        env:
          PROJECTS: ${{ inputs.projects }}
      - name: 'Extract projects'
        id: 'extract_projects'
        uses: actions/github-script@v7.0.0
        env:
          projects: ${{ inputs.projects }}
        with:
          script: |
            const { projects } = process.env;
            const output = process.env.projects.split(',')
              .map((project) => project.trim())
              .filter((project) => project.length > 0);
            if (output.length > 0) {
              return JSON.stringify(output);
            }
            else {
              return ["api-server"];
            }
  deploy:
    needs: extract
    uses: ./.github/workflows/workflow_call_build.yaml
    strategy:
      matrix:
        project: ${{ fromJSON(needs.extract.outputs.projects) }}
    with:
      project: ${{ matrix.project }}
      env: production
      deploy: true
    secrets: inherit
