name: Continuous Deployment (CD)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run CD against'
        type: environment
        default: 'testnet'
        required: true
      projects:
        description: 'Projects to build, (comma separated)'
        required: true
        default: 'apps-api-server, apps-bridge-worker, apps-ethereum-relayer, apps-ethereum-validator, apps-stacks-relayer, apps-stacks-validator'

jobs:
  extract:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      projects: ${{ steps.extract_projects.outputs.result }}
    steps:
      - run: |
          echo "Projects: $PROJECTS"
          echo "Environment: $ENVIRONMENT"
        env:
          PROJECTS: ${{ inputs.projects }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: 'Extract projects'
        id: 'extract_projects'
        uses: actions/github-script@v6.4.1
        env:
          projects: ${{ inputs.projects }}
        with:
          script: |
            return process.env.projects.split(',')
              .map((project) => project.trim())
              .filter((project) => project.length > 0)
  build:
    needs: extract
    uses: ./.github/workflows/workflow_call_build.yaml
    strategy:
      matrix:
        project: ${{ fromJSON(needs.extract.outputs.projects) }}
    with:
      project: ${{ matrix.project }}
      env: ${{ inputs.environment }}
      deploy: true
    secrets: inherit
