name: CI Clarinet

# Controls when the action will run.
on:
  push:
    paths:
      - 'packages/contracts/brc20-indexer-v1/**'

concurrency:
  group: 'ci-clarinet-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  check:
    name: check - ${{ github.ref_name }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # - uses: sergeysova/jq-action@v2
      # - uses: wei/curl@v1
      # - name: Install Deps
      #   run: |
      #     ./scripts/clarinet_manager.sh install
      - name: 'Check contract'
        uses: docker://hirosystems/clarinet:1.5.4
        with:
          entrypoint: 'bash'
          args: -c "cd packages/contracts/brc20-indexer-v1; clarinet check"
  test:
    name: test - ${{ github.ref_name }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # - uses: sergeysova/jq-action@v2
      # - uses: wei/curl@v1
      # - name: Install Deps
      #   run: |
      #     ./scripts/clarinet_manager.sh install
      - name: 'Execute test suite'
        uses: docker://hirosystems/clarinet:1.5.4
        with:
          entrypoint: 'bash'
          args: -c "cd packages/contracts/brc20-indexer-v1; clarinet test"
